<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Oportunidades extends \Entities\Oportunidades implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'id', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'nombre', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'cif', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'cp', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'poblacion', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'operadora', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'lineasmoviles', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'lineasdatos', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'adsl', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'conectapyme', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'historial', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'teleoperadora', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'facturacrm', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fecfactura', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'presupuestocrm', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'coberturacrm', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'preentrcliente', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'citaentrpresupuesto', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fecproxllamada', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fechacita', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'tarea', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'n2', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'n3', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'oferta2', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'oferta3', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'cierra', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fechako', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'converg', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'idusuario', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'idcuenta', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'idfaseventa'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'id', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'nombre', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'cif', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'cp', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'poblacion', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'operadora', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'lineasmoviles', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'lineasdatos', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'adsl', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'conectapyme', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'historial', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'teleoperadora', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'facturacrm', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fecfactura', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'presupuestocrm', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'coberturacrm', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'preentrcliente', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'citaentrpresupuesto', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fecproxllamada', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fechacita', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'tarea', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'n2', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'n3', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'oferta2', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'oferta3', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'cierra', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'fechako', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'converg', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'idusuario', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'idcuenta', '' . "\0" . 'Entities\\Oportunidades' . "\0" . 'idfaseventa'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Oportunidades $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoblacion($poblacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoblacion', [$poblacion]);

        return parent::setPoblacion($poblacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoblacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoblacion', []);

        return parent::getPoblacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperadora($operadora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperadora', [$operadora]);

        return parent::setOperadora($operadora);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperadora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperadora', []);

        return parent::getOperadora();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineasmoviles($lineasmoviles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineasmoviles', [$lineasmoviles]);

        return parent::setLineasmoviles($lineasmoviles);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineasmoviles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineasmoviles', []);

        return parent::getLineasmoviles();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineasdatos($lineasdatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineasdatos', [$lineasdatos]);

        return parent::setLineasdatos($lineasdatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineasdatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineasdatos', []);

        return parent::getLineasdatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsl($adsl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsl', [$adsl]);

        return parent::setAdsl($adsl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsl', []);

        return parent::getAdsl();
    }

    /**
     * {@inheritDoc}
     */
    public function setConectapyme($conectapyme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConectapyme', [$conectapyme]);

        return parent::setConectapyme($conectapyme);
    }

    /**
     * {@inheritDoc}
     */
    public function getConectapyme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConectapyme', []);

        return parent::getConectapyme();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistorial($historial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistorial', [$historial]);

        return parent::setHistorial($historial);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistorial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistorial', []);

        return parent::getHistorial();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeleoperadora($teleoperadora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeleoperadora', [$teleoperadora]);

        return parent::setTeleoperadora($teleoperadora);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeleoperadora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeleoperadora', []);

        return parent::getTeleoperadora();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacturacrm($facturacrm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacturacrm', [$facturacrm]);

        return parent::setFacturacrm($facturacrm);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturacrm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturacrm', []);

        return parent::getFacturacrm();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecfactura($fecfactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecfactura', [$fecfactura]);

        return parent::setFecfactura($fecfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecfactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecfactura', []);

        return parent::getFecfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresupuestocrm($presupuestocrm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresupuestocrm', [$presupuestocrm]);

        return parent::setPresupuestocrm($presupuestocrm);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresupuestocrm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresupuestocrm', []);

        return parent::getPresupuestocrm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoberturacrm($coberturacrm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoberturacrm', [$coberturacrm]);

        return parent::setCoberturacrm($coberturacrm);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoberturacrm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoberturacrm', []);

        return parent::getCoberturacrm();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreentrcliente($preentrcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreentrcliente', [$preentrcliente]);

        return parent::setPreentrcliente($preentrcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreentrcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreentrcliente', []);

        return parent::getPreentrcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCitaentrpresupuesto($citaentrpresupuesto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCitaentrpresupuesto', [$citaentrpresupuesto]);

        return parent::setCitaentrpresupuesto($citaentrpresupuesto);
    }

    /**
     * {@inheritDoc}
     */
    public function getCitaentrpresupuesto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCitaentrpresupuesto', []);

        return parent::getCitaentrpresupuesto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecproxllamada($fecproxllamada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecproxllamada', [$fecproxllamada]);

        return parent::setFecproxllamada($fecproxllamada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecproxllamada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecproxllamada', []);

        return parent::getFecproxllamada();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacita($fechacita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacita', [$fechacita]);

        return parent::setFechacita($fechacita);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacita', []);

        return parent::getFechacita();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarea($tarea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarea', [$tarea]);

        return parent::setTarea($tarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarea', []);

        return parent::getTarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setN2($n2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setN2', [$n2]);

        return parent::setN2($n2);
    }

    /**
     * {@inheritDoc}
     */
    public function getN2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getN2', []);

        return parent::getN2();
    }

    /**
     * {@inheritDoc}
     */
    public function setN3($n3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setN3', [$n3]);

        return parent::setN3($n3);
    }

    /**
     * {@inheritDoc}
     */
    public function getN3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getN3', []);

        return parent::getN3();
    }

    /**
     * {@inheritDoc}
     */
    public function setOferta2($oferta2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOferta2', [$oferta2]);

        return parent::setOferta2($oferta2);
    }

    /**
     * {@inheritDoc}
     */
    public function getOferta2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOferta2', []);

        return parent::getOferta2();
    }

    /**
     * {@inheritDoc}
     */
    public function setOferta3($oferta3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOferta3', [$oferta3]);

        return parent::setOferta3($oferta3);
    }

    /**
     * {@inheritDoc}
     */
    public function getOferta3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOferta3', []);

        return parent::getOferta3();
    }

    /**
     * {@inheritDoc}
     */
    public function setCierra($cierra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCierra', [$cierra]);

        return parent::setCierra($cierra);
    }

    /**
     * {@inheritDoc}
     */
    public function getCierra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCierra', []);

        return parent::getCierra();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechako($fechako)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechako', [$fechako]);

        return parent::setFechako($fechako);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechako()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechako', []);

        return parent::getFechako();
    }

    /**
     * {@inheritDoc}
     */
    public function setConverg($converg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConverg', [$converg]);

        return parent::setConverg($converg);
    }

    /**
     * {@inheritDoc}
     */
    public function getConverg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConverg', []);

        return parent::getConverg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario($idusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcuenta($idcuenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcuenta', [$idcuenta]);

        return parent::setIdcuenta($idcuenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcuenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcuenta', []);

        return parent::getIdcuenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfaseventa($idfaseventa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfaseventa', [$idfaseventa]);

        return parent::setIdfaseventa($idfaseventa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfaseventa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfaseventa', []);

        return parent::getIdfaseventa();
    }

}
