<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cuentas extends \Entities\Cuentas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'id', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'idcomercial', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'nombre', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'numcuenta', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'telefono', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'telefonoalt', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'email', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'cif', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'personacnt', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'direccion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'poblacion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'provincia', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'cp', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'descripcion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'fmodificacion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'fcreacion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'lineasmovil', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'lineasdatos', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'adsl', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'conectapymes', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'centralita', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'centralitas', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'tipocpyme', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'permanencia', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'tpermanencia', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'historial', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'idoperador', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'idusuario', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'modificado', 'cuentasSeguimiento'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'id', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'idcomercial', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'nombre', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'numcuenta', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'telefono', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'telefonoalt', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'email', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'cif', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'personacnt', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'direccion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'poblacion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'provincia', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'cp', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'descripcion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'fmodificacion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'fcreacion', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'lineasmovil', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'lineasdatos', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'adsl', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'conectapymes', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'centralita', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'centralitas', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'tipocpyme', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'permanencia', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'tpermanencia', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'historial', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'idoperador', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'idusuario', '' . "\0" . 'Entities\\Cuentas' . "\0" . 'modificado', 'cuentasSeguimiento'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cuentas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcomercial($idcomercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcomercial', [$idcomercial]);

        return parent::setIdcomercial($idcomercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcomercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcomercial', []);

        return parent::getIdcomercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcuenta($numcuenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcuenta', [$numcuenta]);

        return parent::setNumcuenta($numcuenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcuenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcuenta', []);

        return parent::getNumcuenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoalt($telefonoalt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoalt', [$telefonoalt]);

        return parent::setTelefonoalt($telefonoalt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoalt', []);

        return parent::getTelefonoalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonacnt($personacnt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonacnt', [$personacnt]);

        return parent::setPersonacnt($personacnt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonacnt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonacnt', []);

        return parent::getPersonacnt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoblacion($poblacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoblacion', [$poblacion]);

        return parent::setPoblacion($poblacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoblacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoblacion', []);

        return parent::getPoblacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistorial($historial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistorial', [$historial]);

        return parent::setHistorial($historial);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistorial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistorial', []);

        return parent::getHistorial();
    }

    /**
     * {@inheritDoc}
     */
    public function setFmodificacion($fmodificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFmodificacion', [$fmodificacion]);

        return parent::setFmodificacion($fmodificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFmodificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFmodificacion', []);

        return parent::getFmodificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFcreacion($fcreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFcreacion', [$fcreacion]);

        return parent::setFcreacion($fcreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFcreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFcreacion', []);

        return parent::getFcreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineasmovil($lineasmovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineasmovil', [$lineasmovil]);

        return parent::setLineasmovil($lineasmovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineasmovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineasmovil', []);

        return parent::getLineasmovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineasdatos($lineasdatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineasdatos', [$lineasdatos]);

        return parent::setLineasdatos($lineasdatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineasdatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineasdatos', []);

        return parent::getLineasdatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsl($adsl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsl', [$adsl]);

        return parent::setAdsl($adsl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsl', []);

        return parent::getAdsl();
    }

    /**
     * {@inheritDoc}
     */
    public function setConectapymes($conectapymes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConectapymes', [$conectapymes]);

        return parent::setConectapymes($conectapymes);
    }

    /**
     * {@inheritDoc}
     */
    public function getConectapymes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConectapymes', []);

        return parent::getConectapymes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentralita($centralita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentralita', [$centralita]);

        return parent::setCentralita($centralita);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentralita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentralita', []);

        return parent::getCentralita();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentralitas($centralitas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentralitas', [$centralitas]);

        return parent::setCentralitas($centralitas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentralitas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentralitas', []);

        return parent::getCentralitas();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipocpyme($tipocpyme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipocpyme', [$tipocpyme]);

        return parent::setTipocpyme($tipocpyme);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipocpyme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipocpyme', []);

        return parent::getTipocpyme();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermanencia($permanencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermanencia', [$permanencia]);

        return parent::setPermanencia($permanencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermanencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermanencia', []);

        return parent::getPermanencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpermanencia($tpermanencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpermanencia', [$tpermanencia]);

        return parent::setTpermanencia($tpermanencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpermanencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpermanencia', []);

        return parent::getTpermanencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoperador($idoperador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoperador', [$idoperador]);

        return parent::setIdoperador($idoperador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoperador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperador', []);

        return parent::getIdoperador();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario($idusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setModificado($modificado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModificado', [$modificado]);

        return parent::setModificado($modificado);
    }

    /**
     * {@inheritDoc}
     */
    public function getModificado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModificado', []);

        return parent::getModificado();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuentasseguimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuentasseguimiento', []);

        return parent::getCuentasseguimiento();
    }

}
